spring.application.name=stages-conventions
spring.datasource.url=jdbc:mysql://localhost:3306/stages_conventions?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

server.port = 9092

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


jwt.secret=NjYxZjZlNDIwOTk4ZTJlNjk4ZjJmNjU3YTU5MmU0NDUyYTI4NTQ0NjI4OGU1ZWM4ZjE4OWEzYTcwZTMwYjIwYQ==
jwt.expiration=86400000

# OTP
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = studhass3@gmail.com
spring.mail.password =nvhnivlxlxhcdcds
spring.mail.properties.mail.smtp.auth = true 
spring.mail.properties.mail.smtp.starttls.enable = true


spring.jackson.date-format=dd-MM-yyyy
